- name: Notify Telegram
  # You may pin to the exact commit or the version.
  # uses: yanzay/notify-telegram@1025564e15f68b2fcddeba37b5bfaf4033c79448
  uses: marcos-bah/arRruerra
  with:
    # Chat to send: chat id or @channel_name
    chat: @AsimovProjetosBot
    # Telegram Bot token
    token: 1451127715:AAGD1A3Ri1eeyls-13Qu4iFZWrnQXoUNfN4
    # Job status
    status: done
